name: Auto Deploy Hugo
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build 
        run: hugo -F --cleanDestinationDir
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: chiwu2/chiwu2.github.io
          publish_branch: master
          publish_dir: ./docs
          commit_message: ${{ github.event.head_commit.message }}